test_that("Conversion to igraph", {
  dg1 <- datagraph()
  add_vertex(dg1, list(id = "1"))
  expect_error(add_edge(dg1, from = "1", to = "2"))
  add_vertex(dg1, list(id = "2"))
  add_edge(dg1, from = "1", to = "2")
  expect_true(are_adjacent(dg1, "1", "2"))
  ig1 <- as.igraph(dg1)
  expect_length(V(ig1), 2L)
})
